# Generated by Django 3.2.5 on 2021-10-25 20:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labordelivery', '0001_initial'),
        ('order', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 16, 19, 15, 970720)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='labordelivery',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='labordelivery.labordelivery'),
        ),
    ]
