# Generated by Django 3.2.5 on 2021-08-30 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210712_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 16, 34, 21, 743203)),
        ),
    ]
