# Generated by Django 3.2.5 on 2021-10-25 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211025_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='labordeliverytype',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 25, 18, 19, 33, 896316)),
        ),
    ]
