# Generated by Django 3.2.5 on 2021-10-27 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211025_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='band10count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band10percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band2count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band2percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band3count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band3percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band4count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band4percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band5count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band5percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band6count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band6percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band7count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band7percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band8count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band8percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band9count',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='band9percentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bandstotalcount',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bandstotalpercentage',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 27, 15, 45, 32, 517519)),
        ),
    ]
