# Generated by Django 3.2.5 on 2021-10-28 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211027_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 27, 20, 14, 23, 15856)),
        ),
    ]
