# Generated by Django 3.2.5 on 2021-11-23 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 16, 33, 44, 398366)),
        ),
    ]
